### ISSUE TITLE
[BUG] - transaction date doesn't update

### ISSUE THREAD

**Issue by albertorizzi** [flow-mn/flow#100]
### Bug Description

if I change the transaction date and save, the date doesn't remain memorized

### How to Reproduce

create a transaction and then modify the date

### Expected Behavior

I expected the date changed

### Operating System

iOS 17.4.1

### Flow version (version+build number)

0.3.2+33

### Screenshots

https://github.com/flow-mn/flow/assets/48057685/ee1ffbe2-1cbf-40b2-89ed-7976fe8e6c0e

**Comment by albertorizzi** [comment]
@sadespresso I like very much the app, so I want to improve it. Please accept my apologies if my continual feedback on bugs has inadvertently disrupted the development schedule.

**Comment by sadespresso** [comment]
@albertorizzi it's perfectly fine, I wanna work on the app too :D

Thank you for taking your time to help improve Flow 🥳

**Comment by albertorizzi** [comment]
@sadespresso if i create the expense with date in the past , the date is now. Only if I change the date is updated


https://github.com/flow-mn/flow/assets/48057685/d7f97d5d-7d2d-4484-9408-e5babf9e5100

**Comment by sadespresso** [comment]
It will be fixed on the next release

**Comment by sadespresso** [comment]
I forgot to pass `transactionDate` when creating new transactions, that's why it's always set to `now` when first created 😂

**Comment by albertorizzi** [comment]
> I forgot to pass `transactionDate` when creating new transactions, that's why it's always set to `now` when first created 😂

Don't worry! perfect!
