### ISSUE TITLE
[FEAT] - Next features

### ISSUE THREAD

**Issue by albertorizzi** [flow-mn/flow#118]
### Description

I read all the features in the milestone, but what are the next features implemented?

**Comment by sadespresso** [comment]
Hello there!

I'm not sure. I will come up with something when I have more time :D :D

**Comment by albertorizzi** [comment]
@sadespresso tell me if I can help you to do something, or searching some information about next features

**Comment by sadespresso** [comment]
Currently, all tasks from Release Candidate 1 milestone have been finished.

I'll review the current features and ship a release soon.

After that, I think I'll be able to come up with another milestone✨
