### ISSUE TITLE
l10n: fix "delete" in italian

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#127]
![image](https://github.com/flow-mn/flow/assets/51638223/ffe23c11-770c-4fcb-8232-4ff81105d2d5)

**Comment by albertorizzi** [comment]
I will check tomorrow which translation is correct in this case!

**Comment by albertorizzi** [comment]
"Cancella" in the left button will become "Annulla"
"Cancella" in the right button will become "Elimina"
 And please change in [this line](https://github.com/flow-mn/flow/blob/16383ad1969d2025de903c6d570c6db94740d35b/assets/l10n/it_IT.json#L10) the word "Conferma" with "Confermi".
