### ISSUE TITLE
Launch on FDroid

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#144]
> I am done including fat APK files in the release binary hehe

## Submission for F-Droid

<https://gitlab.com/fdroid/rfp/-/issues/2721>

## Metadata files

I have filled out the above form, and added `fastlane` metadata files. If there's anyone with experience on publishing apps to F-Droid, please help ^^.

**Comment by licaon-kter** [comment]
fyi Objectbox is not FOSS: https://objectbox.io/faq/#license-pricing

**Comment by sadespresso** [comment]
Uh oh...

**Comment by sadespresso** [comment]
@licaon-kter thank you!

I'll try to switch DBs if possible

**Comment by licaon-kter** [comment]
@sadespresso fixed?

**Comment by sadespresso** [comment]
Hello there!

No, holding it for now.

I think I can submit another request after I migrate to SQLite.
