### ISSUE TITLE
[FEAT] [Opt-in] Attach location data to transaction

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#165]
### Description

Attach location data to transaction. This could be used for title suggestion (lol), and to see where the transactions were made.

As this feature requires sensitive permission - location data, this should be opt-in. Although everything will be processed and/or stored on-device.

For visualization, we'll use OSM...

**Comment by MichailIoannou** [comment]
Would really like this feature +1

**Comment by sadespresso** [comment]
Initial draft released in Beta 0.6.2

Next improvements are tracked here: #192
