### ISSUE TITLE
[FEAT] Indian localization 

### ISSUE THREAD

**Issue by chhotuver** [flow-mn/flow#176]
### Description

1: Pleade add notes or description for all three transactions (Income, Expense, Transfer).

2 : Is it possible to display numbers in Indian format for Indian currency (INR). For example :
Now it shows like this : ₹1,000,000
And Indian format : ₹10,00,000
Difference is placement of comma. 

3 : There are not many calendar format (I.e. date format)

**Comment by sadespresso** [comment]
Hello! Thank you for your suggestions.

I think notes would be a good idea.

I'm not sure why Indian currency is displayed incorrectly, I'll look into it.

**Comment by sadespresso** [comment]
@chhotuver Hello there! Can you expand on the suggestion no. 3?

I've added en_IN, so number formatting should be good on the next beta release

**Comment by chhotuver** [comment]
![Screenshot_20240826_100502_Paisa](https://github.com/user-attachments/assets/3533842f-5fd8-438a-95a3-15356bb165bb)
Like this..

**Comment by sadespresso** [comment]
@chhotuver hello there! I've added en_IN locale, should be available on the next beta release.

I've moved the other suggestions to their own issues, so it's easier to work on and track. Please see #179 and #180 for the other two issues.
