### ISSUE TITLE
[FEAT] Closing Balance 

### ISSUE THREAD

**Issue by chhotuver** [flow-mn/flow#181]
### Description

Is it possible to to add closing balance in every transactions for all account. It will be helpful in knowing the balance of past specific dates.

You can also add toggle on/off button in preference.

**Comment by sadespresso** [comment]
This is definitely a good idea, but I'm still thinking on how to handle edits...

Should make it into the app at some point :D D:

**Comment by sadespresso** [comment]
Where do I fit the closing balance neatly 😭

**Comment by chhotuver** [comment]
Besides time or where you like.

**Comment by sadespresso** [comment]
Now the current account ListTile shows the closing balance (balance after the transactions)

This will be available on release beta 0.10.0

This is subject to change.

**Comment by chhotuver** [comment]
Can you please show me where this is in version 0.10.0.
I did not find.

**Comment by sadespresso** [comment]
Hello there!

It's under the account name in transaction page. In older versions, it always showed the current balance of that account, but it's kinda useless. Now it always shows the post-transaction balance for that particular transaction.

It might be a bad design decision, and is subject to change.

Here I circled the post-transaction balance.

![image](https://github.com/user-attachments/assets/cd62e8ed-be4f-4853-a336-04f9596b6874)

On an unrelated note, Happy new year!

**Comment by chhotuver** [comment]
Thanks Understood, I was looking in homepage.
Happy new year
