### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MichailIoannou** [flow-mn/flow#201]
### Bug Description

Transfers neither combine nor are they excluded from balance. Regardless of what setting or restarting.

I have some transactions listed in the past that are properly combined, but doesn't work anymore

### How to Reproduce

Freshly installed app
Add two accounts
Change the transfer settings to combine and not show in total
Add a transfer between the accounts
Shows as separate

### Expected Behavior

One transfer, not in totals as expenses or income

### Operating System

Android

### Flow version (version+build number)

0.7.0-59

**Comment by MichailIoannou** [comment]
For example this is what happens when you transfer back and forth 99 billion euros, it should equal to 0
![Screenshot_20241019-170152_Flow](https://github.com/user-attachments/assets/04eba418-7b8a-406e-9f0b-0cbe39d1076c)
![Screenshot_20241019-170028_Flow](https://github.com/user-attachments/assets/7203a9e9-1b1f-41e0-9894-231f2ba5e2ae)
![Screenshot_20241019-165904_Flow](https://github.com/user-attachments/assets/9bfea62b-1137-4933-b540-fa3a1c11c571)

**Comment by sadespresso** [comment]
Hello there!

Thank you for reporting! I'm on it!

I must've broke 😅
