### ISSUE TITLE
Proper account balance showing

### ISSUE THREAD

**Issue by itsmeshibintmz** [flow-mn/flow#224]
Currently, the account balance is showing like 8.4T for 8400 INR(example). Need a proper value like 8400. It would be better to see insight. Or can add a arrow next to T to show detailed value on drop-down

**Comment by sadespresso** [comment]
Hello there! Can you provide screenshots?

There are multiple place where the account balance is shown, and a screenshot would help identifying it.

As of the current release, all individual account balances do show the full amount

**Comment by itsmeshibintmz** [comment]
![Screenshot_20241114-154940.png](https://github.com/user-attachments/assets/c54fe228-8f40-49c0-96ac-79f344804607)

**Comment by sadespresso** [comment]
Are you referring to the **income**,** expense?**

**Comment by itsmeshibintmz** [comment]
Yes

**Comment by sadespresso** [comment]
Now you can choose to see the full amount by enabling 'Prefer full amounts' in **Settings > Money Formatting**

It may take up to 72 hours before [release beta 0.8.1](https://github.com/flow-mn/flow/releases/tag/0.8.1) is available.

**Comment by itsmeshibintmz** [comment]
Thanks, will check and update here.
