### ISSUE TITLE
[FEAT] Duplicate a transaction

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#232]
A functionality to duplicate a transaction. The new transcation would have every attribute of the original except for the `id` and `uuid`

**Comment by alessiozanutta** [comment]
is there a reason for not being able to duplicate a transfer transaction?
it would be useful to follow the same approach as the other transactions since there's no option to put recurring transactions yet.

**Comment by sadespresso** [comment]
Not really any major reason. But if user has chosen to show transfers
separately, it looks little weird duplicating one of them resulting in two
new transactions…


Batmend Ganbaatar

Developer

Stora Central LLC

***@***.***

+976 8804 9259 <+97688049259>

<https://github.com/sadespresso>

<https://www.instagram.com/yourstepbf/>

<https://www.facebook.com/sadespress0/>

***@***.***>

<https://twitter.com/sadespresso_>

<https://www.linkedin.com/in/batmend-ganbaatar-711968193/>

Please let me know if you believe you received this email by an accident ✌️

**Comment by sadespresso** [comment]
Not really any major reason. But if user has chosen to show transfers separately, it looks little weird duplicating one of them resulting in two new transactions…

**Comment by sadespresso** [comment]
I think I thought duplicating transfers wouldn't have that much use... I can enable it if it occurs to be a common case for you, or others
