### ISSUE TITLE
Improve setup category preset selection

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#68]
* Maybe add a `Select all` button
* Show how many presets have been selected so far

![image](https://github.com/flow-mn/flow/assets/51638223/9a79171d-8174-44c5-8378-d2d134c3b2bf)

**Comment by albertorizzi** [comment]
I like very much the Setup categories, but it can be a good solution if it's possible to add the preset selection also in the edit page in setting page @sadespresso

**Comment by sadespresso** [comment]
@albertorizzi that is actually a really nice idea, thank you!

**Comment by sadespresso** [comment]
This has been fixed in #103
