### ISSUE TITLE
[FEAT] Desktop fixes / UI/UX compability

### ISSUE THREAD

**Issue by ghost** [flow-mn/flow#90]
### Description

1. First page of Setup overflowed
![2024-03-11T11:49:24,666203089+05:00](https://github.com/flow-mn/flow/assets/124512007/3c5a218d-2762-4603-889a-3efc44f32305)
2. Use SVG for missing texture: desktop crop png image (use flutter_svg dep)
3. Fix proportions of widgets (MediaQuery)
![2024-03-11T11:51:47,416354573+05:00](https://github.com/flow-mn/flow/assets/124512007/6f8d789a-2e55-42c3-ad87-9b535c4dbd97)
4. Russian locale
5. class SelectAccountSheet pop on dismiss returns bool instead Account (error)

### Additional Context

I'm working on it

**Comment by rustzzdevel** [comment]
6. Keyboard scale invalid
![2024-03-11T12:24:08,794090276+05:00](https://github.com/flow-mn/flow/assets/124512007/cf68f387-bbd8-41d4-8f45-65ac55403e3b)

**Comment by sadespresso** [comment]
Hello there! Thank you for your work to make Flow better. At the moment, Flow doesn't support desktop. Until we officially release, no major work will be done on Flow's desktop UI/UX.

**Comment by rustzzdevel** [comment]
@sadespresso Can you check my edits? I think it will allow Android and Desktop to work as well
