### ISSUE TITLE
[BUG] - untitled transaction

### ISSUE THREAD

**Issue by albertorizzi** [flow-mn/flow#96]
### Bug Description

I can’t add new title transaction.

### How to Reproduce

Add a transaction and write something in the title. In the home page appear “Untitled transaction”

### Expected Behavior

I expect the title I wrote

### Operating System

iOS 17.4.1

### Flow version (version+build number)

0.3.3+33

### Screenshots

https://github.com/flow-mn/flow/assets/48057685/de822e22-bdeb-45c1-9474-77a743f1128b

**Comment by sadespresso** [comment]
Thank you for reporting the issue. I can reproduce it.

I kept using transaction title from previous transactions, so i didn't encounter this 😔

Will fix this asap 🚀

**Comment by albertorizzi** [comment]
When do you plan to release this fix? @sadespresso

**Comment by sadespresso** [comment]
Oh, I fixed it and released it.

**Comment by sadespresso** [comment]
I will make release post on GitHub in a moment

**Comment by sadespresso** [comment]
https://github.com/flow-mn/flow/releases/tag/0.3.2

**Comment by albertorizzi** [comment]
Fantastic!
